# Generated by Django 4.2 on 2024-04-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0002_aboutme_blog_contact_portfolio_skill_timeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
