# Generated by Django 5.0.6 on 2024-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0003_blog_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="percentage",
        ),
        migrations.AddField(
            model_name="aboutme",
            name="image",
            field=models.ImageField(default=1, upload_to="Images"),
            preserve_default=False,
        ),
    ]
