# Generated by Django 5.0.6 on 2024-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0006_timeline_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.ImageField(default=1, upload_to="", verbose_name="/Images"),
            preserve_default=False,
        ),
    ]
