# Generated by Django 5.0.6 on 2024-05-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0007_skill_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutme",
            name="cv_link",
        ),
        migrations.AddField(
            model_name="aboutme",
            name="cv_file",
            field=models.FileField(default=1, upload_to="cv_uploads/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="skill",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="/Images"
            ),
        ),
    ]
