# Generated by Django 5.0.6 on 2024-05-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0008_remove_aboutme_cv_link_aboutme_cv_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="GPA",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="education",
            name="year",
            field=models.CharField(max_length=100),
        ),
    ]
