# Generated by Django 5.0.6 on 2024-05-23 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0010_alter_skill_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="introduction",
            name="cv_link",
        ),
        migrations.RemoveField(
            model_name="introduction",
            name="description",
        ),
    ]
