# Generated by Django 5.0.6 on 2024-10-08 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0011_remove_introduction_cv_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeline",
            name="skills",
        ),
    ]
